<?php

namespace An1zhegorodov\JQueueBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    public function pop($workerId, $jobTypeId)
    {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $table = $this->getClassMetadata()->getTableName();
        $query = sprintf('
            UPDATE %s
            SET status_id = :started_status_id,
            worker_id = :worker_id
            WHERE type_id = :type_id
            AND status_id = :new_status_id
            AND worker_id = 0
            ORDER BY created ASC
            limit 1
        ', $table);
        $connection->executeUpdate($query, array(
            ':started_status_id'    => JobStatuses::STARTED,
            ':type_id'              => $jobTypeId,
            ':worker_id'            => $workerId,
            ':new_status_id'        => JobStatuses::SNEW,
        ));

        $qb = $this->createQueryBuilder('j');
        $qb->where('j.typeId = :type_id')
            ->andWhere('j.statusId = :started_status_id')
            ->andWhere('j.workerId = :worker_id')
            ->setMaxResults(1);
        $qb->setParameters(array(
            'type_id' => $jobTypeId,
            'started_status_id' => JobStatuses::STARTED,
            'worker_id' => $workerId
        ));

        return $qb->getQuery()->getSingleResult();
    }
}
